/*
=============================================================================
  CHOP Unified Admin Setup — Workshop Participant Role Assignment
  Script: all_user_workshop_assignment.sql
=============================================================================
  Run as: ACCOUNTADMIN
  Prerequisites: Section 2 (roles and grants)

  Assigns all 95 April 14th workshop registrants to:
    CHOP_SNOW_INTELLIGENCE  (workshop access — Snowflake Intelligence use case)
    AI_EXPLORER             (cost governance — $50/month cap)

  Generated from sign-up form: April 14th workshop (9am–2:30pm)
  Total participants: 95
=============================================================================
*/
USE ROLE ACCOUNTADMIN;

-- ========= WORKSHOP PARTICIPANTS — April 14, 2026 =========
-- All users granted BOTH:
--   CHOP_SNOW_INTELLIGENCE (workshop access)
--   AI_EXPLORER            (cost governance)

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER TARIQA3@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER TARIQA3@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER OLUWALADEB@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER OLUWALADEB@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MAIERD@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MAIERD@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER TOOHEYL@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER TOOHEYL@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER ELAMROUSYS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER ELAMROUSYS@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER CORSOS1@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER CORSOS1@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER BHAWSARR@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER BHAWSARR@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER DONNELLAND@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER DONNELLAND@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER DYEM1@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER DYEM1@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER XINF@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER XINF@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER NANDAGOPAD@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER NANDAGOPAD@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KUMARM3@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KUMARM3@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER DUDHIAA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER DUDHIAA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER BORKARV@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER BORKARV@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER RUSSANOA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER RUSSANOA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MUSKAJA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MUSKAJA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER TICKNERM@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER TICKNERM@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER NAYARV@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER NAYARV@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KANTIPUDIJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KANTIPUDIJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER VACCAROB@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER VACCAROB@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MATHEWS5@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MATHEWS5@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER SHETTYA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER SHETTYA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MAINOJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MAINOJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KANDUKURIS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KANDUKURIS@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MACMULLENB@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MACMULLENB@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER SHUBHAMURS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER SHUBHAMURS@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MERRILLDR@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MERRILLDR@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER REILLYS2@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER REILLYS2@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MIRIZIOJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MIRIZIOJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER HAMIDAC@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER HAMIDAC@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER ZORC@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER ZORC@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER SONGW1@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER SONGW1@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER TURLINGTOR@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER TURLINGTOR@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER FERNANDEZG@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER FERNANDEZG@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER COSTELLOR@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER COSTELLOR@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER RUDOFKERA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER RUDOFKERA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KHAITANN@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KHAITANN@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER SALEEMS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER SALEEMS@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MORENOCOSV@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MORENOCOSV@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER SHAHT3@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER SHAHT3@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER GEETIKAF@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER GEETIKAF@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER CHIUR3@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER CHIUR3@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MANIERIM@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MANIERIM@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER CIARLANTEA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER CIARLANTEA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MADASJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MADASJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER ASHWARYAK@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER ASHWARYAK@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER PIMPLEYS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER PIMPLEYS@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER BALAJIM@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER BALAJIM@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KINTZINGJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KINTZINGJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER RILEYJ3@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER RILEYJ3@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER NAINARD@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER NAINARD@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KRISHNAMUD@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KRISHNAMUD@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER APONTEP@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER APONTEP@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER PLESKUNASE@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER PLESKUNASE@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MURALIDHAB@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MURALIDHAB@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KANEJ8@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KANEJ8@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER JACOBSMAN@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER JACOBSMAN@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER OLIVERAJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER OLIVERAJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER DAGOSTINOL@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER DAGOSTINOL@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KENNEDYA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KENNEDYA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER PEREZIBARL@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER PEREZIBARL@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER BALOGHB@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER BALOGHB@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER YARNALLJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER YARNALLJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER WANGM9@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER WANGM9@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER COLLINSD1@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER COLLINSD1@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER GEBERTC@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER GEBERTC@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER ZUCKMAND@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER ZUCKMAND@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER WUXX@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER WUXX@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER WELSCH@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER WELSCH@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER ALIDJANIS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER ALIDJANIS@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER NEWBURNP@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER NEWBURNP@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER NELSONKL@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER NELSONKL@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER TUCKERG2@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER TUCKERG2@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER ALTAMEEMIH@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER ALTAMEEMIH@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER URICKJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER URICKJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER NV@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER NV@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER HAWKINSRT@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER HAWKINSRT@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER ZHOUY11@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER ZHOUY11@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER WILLIAMA22@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER WILLIAMA22@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER WINSERK@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER WINSERK@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER SCHMIDJ@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER SCHMIDJ@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER TOMASKOVIS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER TOMASKOVIS@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER CURRYB1@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER CURRYB1@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER YOUSSEFA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER YOUSSEFA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER BRANDEMARTEA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER BRANDEMARTEA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER PARRISHB2@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER PARRISHB2@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER GOODWINJL@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER GOODWINJL@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KIRCHNERV@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KIRCHNERV@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER PATILO@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER PATILO@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER BARMAR@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER BARMAR@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER MEREDITHM@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER MEREDITHM@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER CARMONAPAC@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER CARMONAPAC@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER JAVIAA@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER JAVIAA@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER KABATD@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER KABATD@CHOP.EDU;

GRANT ROLE CHOP_SNOW_INTELLIGENCE TO USER CALLAHANS@CHOP.EDU;
GRANT ROLE AI_EXPLORER             TO USER CALLAHANS@CHOP.EDU;

SELECT 'Workshop participant role assignment complete: 95 users granted CHOP_SNOW_INTELLIGENCE + AI_EXPLORER' AS STATUS;
