/*
=============================================================================
  CHOP Infrastructure Setup Guide — Section 3: SI Source Tables & Synthetic Data
  Script 02: Base tables + synthetic data generation (DEMO ACCOUNT ONLY)
=============================================================================
  Run as: ACCOUNTADMIN
  ONLY on demo/SE accounts, NOT on CHOP production
  File ref: example_chop/for_your_demo_account/00_base_tables_chop.sql
            example_chop/for_your_demo_account/01_synthetic_datagen_chop.sql
  Prerequisites: None
=============================================================================
*/
USE ROLE ACCOUNTADMIN;

-- Create source databases (mirroring CHOP's structure)
CREATE DATABASE IF NOT EXISTS PROD
    COMMENT = 'Demo mirror of CHOP PROD database for SI testing';
CREATE SCHEMA IF NOT EXISTS PROD.LAKE_HDMS
    COMMENT = 'Demo mirror of HDMS pharmacy data lake';
CREATE SCHEMA IF NOT EXISTS PROD.SEMANTIC
    COMMENT = 'Demo mirror of semantic layer';

-- Table 1: DS_PHARMACY_ALLMEDICALSCRIPTS (45 columns)
CREATE OR REPLACE TABLE PROD.LAKE_HDMS.DS_PHARMACY_ALLMEDICALSCRIPTS (
    SCRIPTNUMBER INTEGER, ACCOUNT INTEGER,
    PATIENTFULLNAME VARCHAR, PATIENTFIRSTNAME VARCHAR, PATIENTLASTNAME VARCHAR,
    PATIENTGENDER VARCHAR, PATIENTBIRTHDATE TIMESTAMP, PATIENTZIP VARCHAR,
    PHYSICIANIDENTIFIER INTEGER, PHYSICIAN_LASTNAME VARCHAR,
    PHYSICIAN_FIRSTNAME VARCHAR, PHYSICIAN_DEGREE VARCHAR,
    PHYSICIAN_NPI VARCHAR, PHYSICIAN_DEA VARCHAR,
    FIRST_DELIVERYDATE TIMESTAMP, LAST_DELIVERYDATE TIMESTAMP,
    DRUGPRODUCTCODE VARCHAR, DRUGDESCRIPTION VARCHAR, NDC VARCHAR,
    DRUGPRODUCTVENDORCOST NUMERIC(19,4), COSTAVERAGE NUMERIC(19,4),
    DRUGPRODUCTCATEGORY VARCHAR,
    RXSTARTDATE TIMESTAMP, RXENDDATE TIMESTAMP,
    PRESCRIPTIONQUANTITY FLOAT, REFILLS SMALLINT, REFILLSREMAINING SMALLINT,
    PRESCRIPTIONSERIALNUMBER VARCHAR, PRESCRIPTIONDISCONTINUED SMALLINT,
    DISPENSEDASWRITTENVALUE SMALLINT,
    DOSEDETAILS FLOAT, DOSEUOM VARCHAR, DOSEVOLUME FLOAT,
    DOSESPERDAY FLOAT, DOSAGEFREQUENCY VARCHAR, ADMINROUTE VARCHAR,
    CATHETERTYPE VARCHAR, THERAPYTYPE VARCHAR,
    ADMINISTRATIONDIRECTIONS VARCHAR, COMPOUNDINGDIRECTIONS VARCHAR,
    RX_DX1 VARCHAR, RX_DX2 VARCHAR, RX_DX3 VARCHAR,
    PRIMARY_PAYERNAME VARCHAR, PRIMARY_PAYERTYPENAME VARCHAR
);

-- Table 5: MEDICATION_ORDER_ALL (48 columns)
CREATE OR REPLACE TABLE PROD.SEMANTIC.MEDICATION_ORDER_ALL (
    MEDICATION_ORDER_KEY VARCHAR, PATIENT_NAME VARCHAR, MRN VARCHAR,
    PATIENT_KEY VARCHAR, ENCOUNTER_KEY VARCHAR, MEDICATION_KEY VARCHAR,
    DOB DATE, CSN VARCHAR, SEX VARCHAR, ENCOUNTER_DATE DATE,
    MEDICATION_ORDER_ID VARCHAR, MEDICATION_ORDER_CREATE_DATE TIMESTAMP,
    MEDICATION_ORDER_NAME VARCHAR, MEDICATION_START_DATE DATE,
    MEDICATION_END_DATE DATE, MEDICATION_NAME VARCHAR, MEDICATION_ID VARCHAR,
    MEDICATION_FORM VARCHAR, MEDICATION_STRENGTH VARCHAR,
    GENERIC_MEDICATION_NAME VARCHAR, GENERIC_PRODUCT_IDENTIFIER VARCHAR,
    THERAPEUTIC_CLASS VARCHAR, THERAPEUTIC_CLASS_ID VARCHAR,
    PHARMACY_CLASS VARCHAR, PHARMACY_CLASS_ID VARCHAR,
    PHARMACY_SUB_CLASS VARCHAR, PHARMACY_SUB_CLASS_ID VARCHAR,
    SPECIALTY_MEDICATION_IND INTEGER, ORDER_DOSE VARCHAR,
    ORDER_DOSE_UNIT VARCHAR, ORDER_ROUTE VARCHAR, ORDER_ROUTE_GROUP VARCHAR,
    FORMULARY_MED_IND INTEGER, QUANTITY FLOAT,
    N_REFILLS_ALLOWED INTEGER, N_REFILLS_REMAINING INTEGER,
    PHARMACY_ID VARCHAR, PHARMACY_NAME VARCHAR, ORDER_FREQUENCY VARCHAR,
    ORDER_MODE VARCHAR, ORDER_CLASS VARCHAR, HISTORICAL_MED_IND INTEGER,
    CONTROL_MED_IND INTEGER, DEA_CODE_ID VARCHAR, DEA_CLASS_CODE VARCHAR,
    ACTIVE_ORDER_STATUS VARCHAR, PENDING_IND INTEGER, DISCHARGE_MED_IND INTEGER
);

-- NOTE: Tables 2-4 and 6 are in 00_base_tables_chop.sql
-- For the complete set, run the full file:
--   CHOP_snowflake-intelligence-accelerator-main/example_chop/for_your_demo_account/00_base_tables_chop.sql

-- =============================================================================
-- SYNTHETIC DATA GENERATION
-- Run AFTER 00_base_tables_chop.sql AND 01_si_infrastructure.sql
-- =============================================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE CHOP_snow_intelligence_WH;

-- The datagen procedure is created by running the full file:
--   example_chop/for_your_demo_account/01_synthetic_datagen_chop.sql
-- Then call it with your desired scale:

-- TINY:   100 prescriptions   (quick test)
-- SMALL:  1,000 prescriptions (default, good for demos)
-- MEDIUM: 10,000 prescriptions
-- LARGE:  50,000 prescriptions

CALL SI_CHOP.CHOP_SNOW_INTELLIGENCE.GENERATE_CHOP_SYNTHETIC_DATA('SMALL');
