/*
=============================================================================
  CHOP Infrastructure Setup Guide — Section 9: Healthcare ML Infrastructure
  Script 08: Database, schemas, warehouse, source tables, stage
=============================================================================
  Run as: ACCOUNTADMIN
  Prerequisites: None
  File ref: healthcare-readmission-ml/scripts/admin_setup_infrastructure.sql
=============================================================================
*/
USE ROLE ACCOUNTADMIN;

-- 1. DATABASE
CREATE DATABASE IF NOT EXISTS HEALTHCARE_ML
    COMMENT = 'Healthcare 30-day readmission prediction ML pipeline';

-- 2. SCHEMAS
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ML.RAW_DATA
    COMMENT = 'Source EHR data: patients, admissions, clinical measurements';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ML.FEATURE_STORE
    COMMENT = 'Snowflake Feature Store: entities, feature views, dynamic tables';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ML.MODEL_REGISTRY
    COMMENT = 'Snowflake Model Registry: trained models and versions';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ML.INFERENCE
    COMMENT = 'Batch and real-time inference outputs';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ML.GIT_INTEGRATION
    COMMENT = 'Git repository integration objects for ML pipeline code';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ML.TASKS
    COMMENT = 'Scheduled pipeline tasks (git fetch, batch scoring)';

-- 3. WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS HEALTHCARE_ML_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse for Healthcare ML pipeline';

-- 4. SOURCE TABLES
USE SCHEMA HEALTHCARE_ML.RAW_DATA;

-- Table 1: PATIENTS — Patient demographics (6 columns)
CREATE TABLE IF NOT EXISTS HEALTHCARE_ML.RAW_DATA.PATIENTS (
    PATIENT_ID     VARCHAR(10) NOT NULL,
    AGE            INTEGER,
    GENDER         VARCHAR(1),
    INSURANCE_TYPE VARCHAR(20),
    ZIP_CODE       VARCHAR(10),
    HAS_PCP        BOOLEAN,
    CONSTRAINT PK_PATIENTS PRIMARY KEY (PATIENT_ID)
);

-- Table 2: ADMISSIONS — Hospital admission records (11 columns)
CREATE TABLE IF NOT EXISTS HEALTHCARE_ML.RAW_DATA.ADMISSIONS (
    ADMISSION_ID          VARCHAR(10) NOT NULL,
    PATIENT_ID            VARCHAR(10) NOT NULL,
    ADMIT_DATE            DATE,
    DISCHARGE_DATE        DATE,
    LENGTH_OF_STAY        INTEGER,
    PRIMARY_DIAGNOSIS     VARCHAR(50),
    NUM_PROCEDURES        INTEGER,
    NUM_DIAGNOSES         INTEGER,
    DISCHARGE_DISPOSITION VARCHAR(20),
    ED_ADMISSION          INTEGER,
    READMITTED_30D        INTEGER,
    CONSTRAINT PK_ADMISSIONS PRIMARY KEY (ADMISSION_ID)
);

-- Table 3: CLINICAL_MEASUREMENTS — Vitals & labs at discharge (16 columns)
CREATE TABLE IF NOT EXISTS HEALTHCARE_ML.RAW_DATA.CLINICAL_MEASUREMENTS (
    ADMISSION_ID     VARCHAR(10) NOT NULL,
    PATIENT_ID       VARCHAR(10) NOT NULL,
    MEASUREMENT_DATE DATE,
    HEART_RATE       FLOAT, SYSTOLIC_BP      FLOAT, DIASTOLIC_BP FLOAT,
    TEMPERATURE      FLOAT, RESPIRATORY_RATE FLOAT, O2_SATURATION FLOAT,
    BLOOD_GLUCOSE    FLOAT, CREATININE       FLOAT, HEMOGLOBIN    FLOAT,
    WBC_COUNT        FLOAT, SODIUM           FLOAT, POTASSIUM     FLOAT,
    BNP              FLOAT
);

-- Table 4: TRAINING_DATA — 34 engineered feature columns
CREATE TABLE IF NOT EXISTS HEALTHCARE_ML.RAW_DATA.TRAINING_DATA (
    AGE INTEGER, GENDER_ENC INTEGER, INSURANCE_ENC INTEGER, HAS_PCP_FLAG INTEGER,
    LENGTH_OF_STAY INTEGER, NUM_PROCEDURES INTEGER, NUM_DIAGNOSES INTEGER,
    DIAGNOSIS_RISK_SCORE INTEGER, DISPOSITION_RISK_SCORE INTEGER, ED_ADMISSION INTEGER,
    HEART_RATE FLOAT, SYSTOLIC_BP FLOAT, DIASTOLIC_BP FLOAT,
    TEMPERATURE FLOAT, RESPIRATORY_RATE FLOAT, O2_SATURATION FLOAT,
    BLOOD_GLUCOSE FLOAT, CREATININE FLOAT, HEMOGLOBIN FLOAT,
    WBC_COUNT FLOAT, SODIUM FLOAT, POTASSIUM FLOAT, BNP FLOAT,
    ABNORMAL_HR INTEGER, ABNORMAL_BP INTEGER, LOW_O2 INTEGER,
    HIGH_CREATININE INTEGER, LOW_HEMOGLOBIN INTEGER, HIGH_BNP INTEGER,
    ABNORMAL_GLUCOSE INTEGER, PRIOR_ADMISSIONS_6M INTEGER,
    PRIOR_READMISSIONS INTEGER, AVG_PRIOR_LOS FLOAT, READMITTED_30D INTEGER
);

-- Table 5: TEST_DATA — same 34 columns as TRAINING_DATA
CREATE TABLE IF NOT EXISTS HEALTHCARE_ML.RAW_DATA.TEST_DATA (
    AGE INTEGER, GENDER_ENC INTEGER, INSURANCE_ENC INTEGER, HAS_PCP_FLAG INTEGER,
    LENGTH_OF_STAY INTEGER, NUM_PROCEDURES INTEGER, NUM_DIAGNOSES INTEGER,
    DIAGNOSIS_RISK_SCORE INTEGER, DISPOSITION_RISK_SCORE INTEGER, ED_ADMISSION INTEGER,
    HEART_RATE FLOAT, SYSTOLIC_BP FLOAT, DIASTOLIC_BP FLOAT,
    TEMPERATURE FLOAT, RESPIRATORY_RATE FLOAT, O2_SATURATION FLOAT,
    BLOOD_GLUCOSE FLOAT, CREATININE FLOAT, HEMOGLOBIN FLOAT,
    WBC_COUNT FLOAT, SODIUM FLOAT, POTASSIUM FLOAT, BNP FLOAT,
    ABNORMAL_HR INTEGER, ABNORMAL_BP INTEGER, LOW_O2 INTEGER,
    HIGH_CREATININE INTEGER, LOW_HEMOGLOBIN INTEGER, HIGH_BNP INTEGER,
    ABNORMAL_GLUCOSE INTEGER, PRIOR_ADMISSIONS_6M INTEGER,
    PRIOR_READMISSIONS INTEGER, AVG_PRIOR_LOS FLOAT, READMITTED_30D INTEGER
);

-- FILE FORMAT & STAGE for CSV upload
CREATE FILE FORMAT IF NOT EXISTS HEALTHCARE_ML.RAW_DATA.CSV_FORMAT
    TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1 NULL_IF = ('', 'NULL', 'None') TRIM_SPACE = TRUE;

CREATE STAGE IF NOT EXISTS HEALTHCARE_ML.RAW_DATA.DATA_UPLOAD_STAGE
    FILE_FORMAT = HEALTHCARE_ML.RAW_DATA.CSV_FORMAT
    COMMENT = 'Stage for uploading CSV source data files';
